import { Chart, registerables } from 'chart.js';
import { createCanvas } from 'canvas';
import type { ChartData, ChartDataPoint, VpdRange, VpdStage } from './types.js';
import { STAGE_THRESHOLDS } from './vpd.js';

Chart.register(...registerables);

/**
 * Configuration for rendering the VPD chart.
 */
export interface ChartRenderOptions {
  /** The growth stage for which the chart data was generated. */
  stage: VpdStage;
  /** Width of the chart image in pixels. */
  width?: number;
  /** Height of the chart image in pixels. */
  height?: number;
  /** Title of the chart. */
  title?: string;
}

/**
 * Maps VPD ranges to colors for chart visualization.
 */
const RANGE_COLORS: Record<VpdRange, string> = {
  low: 'rgba(255, 99, 132, 0.7)', // Red
  optimal: 'rgba(75, 192, 192, 0.7)', // Green
  high: 'rgba(255, 205, 86, 0.7)', // Yellow
};

/**
 * Renders a VPD chart as a PNG buffer.
 * @param chartData - The data generated by `generateChartData`.
 * @param options - Rendering options for the chart.
 * @returns A Promise that resolves to a Buffer containing the PNG image data.
 */
export async function renderVpdChart(chartData: ChartData, options: ChartRenderOptions): Promise<Buffer> {
  const { stage, width = 800, height = 600, title } = options;

  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');

  const temperatures = Array.from(new Set(chartData.points.map(p => p.temperatureC))).sort((a, b) => a - b);
  const humidities = Array.from(new Set(chartData.points.map(p => p.humidityPercent))).sort((a, b) => a - b);

  const datasets = Object.keys(RANGE_COLORS).map((rangeKey: VpdRange) => {
    const rangePoints = chartData.points.filter(p => p.range === rangeKey);
    return {
      label: `${rangeKey.charAt(0).toUpperCase() + rangeKey.slice(1)} VPD`, // Capitalize first letter
      data: rangePoints.map(p => ({ x: p.temperatureC, y: p.humidityPercent, vpd: p.vpd })),
      backgroundColor: RANGE_COLORS[rangeKey],
      borderColor: RANGE_COLORS[rangeKey].replace('0.7', '1'),
      pointRadius: 5,
      pointHoverRadius: 7,
      showLine: false,
      type: 'scatter' as const,
    };
  });

  const vpdThresholds = STAGE_THRESHOLDS[stage];

  // Add threshold lines
  datasets.push({
    label: `Low VPD Threshold (${vpdThresholds.low} kPa)`, 
    data: temperatures.map(t => ({ x: t, y: 0 })), // Placeholder, actual line will be drawn by plugin
    borderColor: 'rgba(255, 99, 132, 1)',
    borderWidth: 2,
    borderDash: [5, 5],
    fill: false,
    pointRadius: 0,
    type: 'line' as const,
    hidden: true, // Hide from legend
  });

  datasets.push({
    label: `High VPD Threshold (${vpdThresholds.high} kPa)`, 
    data: temperatures.map(t => ({ x: t, y: 0 })), // Placeholder
    borderColor: 'rgba(255, 205, 86, 1)',
    borderWidth: 2,
    borderDash: [5, 5],
    fill: false,
    pointRadius: 0,
    type: 'line' as const,
    hidden: true, // Hide from legend
  });

  new Chart(ctx, {
    type: 'scatter',
    data: {
      datasets: datasets,
    },
    options: {
      responsive: false,
      maintainAspectRatio: false,
      plugins: {
        title: {
          display: true,
          text: title || `VPD Chart for ${stage.charAt(0).toUpperCase() + stage.slice(1)} Stage`,
          font: { size: 18 },
        },
        tooltip: {
          callbacks: {
            label: function(context) {
              const point = context.raw as { x: number; y: number; vpd: number };
              return `Temp: ${point.x}°C, RH: ${point.y}%, VPD: ${point.vpd.toFixed(2)} kPa`;
            },
          },
        },
      },
      scales: {
        x: {
          type: 'linear',
          position: 'bottom',
          title: {
            display: true,
            text: 'Temperature (°C)',
          },
          min: Math.min(...temperatures),
          max: Math.max(...temperatures),
          grid: { drawOnChartArea: true },
        },
        y: {
          type: 'linear',
          title: {
            display: true,
            text: 'Relative Humidity (%)',
          },
          min: Math.min(...humidities),
          max: Math.max(...humidities),
          grid: { drawOnChartArea: true },
        },
      },
    },
  });

  return canvas.toBuffer('image/png');
}
